---
abstract: "use in-'mem' version of current package"
author:
  - 'Linda Walsh (perl-diddler@tlinx.org)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: mem
no_index:
  directory:
    - t
    - inc
requires:
  Test::Simple: 0.44
version: v0.3.0
