---
abstract: "allow use of packages already in 'mem'ory"
author:
  - 'Linda Walsh (LAWALSH@cpan.org)'
build_requires:
  ExtUtils::MakeMaker: 0
  Test::Simple: 0.44
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.82, CPAN::Meta::Converter version 2.132830'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: mem
no_index:
  directory:
    - t
    - inc
requires: {}
version: v0.4.1
